# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'colorie-counter' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for colorie-counter

  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/MLVision'
  pod 'Firebase/MLVisionBarcodeModel'

end
